server:
  port: 8189
  servlet:
    context-path: /app
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shop_new
    username: postgres
    password: root
  jpa:
    show-sql: true
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create-drop
  sql:
    init:
      platform: postgres
other:
  cache:
    cart: "Cart"