//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.08.22 at 09:46:57 PM MSK
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mvg.com/spring/ws/users", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package spring.soap;
