INSERT INTO product_table (title, price)
VALUES ('Chocolate bar', 99),
       ('Bacon-flavored crisps', 107),
       ('Sparkling water', 75),
       ('Canned tuna', 201),
       ('Instant coffee', 412),
       ('Ice cream', 149),
       ('Cookies', 309),
       ('Sour cream', 95),
       ('Juice', 189),
       ('Broccoli', 259),
       ('Pineapple', 699),
       ('Strawberry', 109),
       ('Chicken mince', 179),
       ('Beef', 499),
       ('Meat dumplings', 349),
       ('Pizza', 229),
       ('Cherry', 179),
       ('Bread', 84),
       ('Focaccia', 159),
       ('Oat milk', 159);
