server:
  port: 8189
  servlet:
    context-path: /market
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_shop
    username: postgres
    password: Qwe123
    hikari:
      schema: cart_schema
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: true
  jpa:
    show-sql: true
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create-drop
  sql:
    init:
      platform: postgres

  redis:
    database: 0
    host: localhost
    port: 6379
    password:
  cache:
    default:
      expire-time: 700000000
    user:
      expire-time: 700000000
      name: Cart
  eureka:
    instance:
      hostname: ticket-service
    client:
      serviceUrl:
        defaultZone: ${EUREKA_URI:http://discovery:8700/eureka}
        fetchRegistry: false
#other:
#  cache:
#    cart: "Cart"